In [1]:
# Import necessary library
import torch as th
import torch.nn as nn
from torch.optim import SGD
import math

In [2]:
# Max Pooling Function
def maxpooling(a):
    '''
        Compute the 2D max pooling (assuming shape of the pooling window is 2 by 2).
        Input:
            a:  the feature map of one instance, a float torch Tensor of shape (n by n_filter by h by w). n is the batch size, n_filter is the number of filters in Conv2D.
                h and w are height and width after ReLU.
        Output:
            p: the tensor after max pooling, a float torch tensor of shape n by n_filter by floor(h/2) by floor(w/2).
        Note: please do NOT use torch.nn.MaxPool2d or torch.nn.functional.max_pool2d or max_pool1d, implement your own version using only basic tensor operations.
        Note: if there are mulitple max values, select the one with the smallest index.
    '''
    #########################################
    # INSERT YOUR CODE HERE
    n, n_filter, h, w = a.shape  # return all the dimension of the filter

    # Initilize the tensor after pooling
    p = th.zeros((n, n_filter, math.floor(h / 2), math.floor(w / 2)))

    # Iterate over n, n_filter,h, and w
    # Here, remmber to keep track of pooling layer index by dividing by 2
    for i in range(n):
        for j in range(n_filter):
            for k in range(0, h - 1, 2):
                for l in range(0, w - 1, 2):
                    p[i, j, int(k / 2), int(l / 2)] = th.max(a[i, j, k:k + 2, l:l + 2])
    #########################################
    return p

In [3]:
# Create two tensor for testing
a = th.tensor([[[[ 0., 1.],
                     [ 1., 0.]]]],requires_grad=True)

a_true = th.tensor([[[[ 0., 1.],
                          [ 1., 0.]]]],requires_grad=True)

In [4]:
p = maxpooling(a) # using our own implementation maxpool
p_true = th.nn.functional.max_pool2d(a_true,kernel_size=2) # using the library in pytroch

In [5]:
p

tensor([[[[1.]]]], grad_fn=<CopySlices>)

In [6]:
p_true

tensor([[[[1.]]]], grad_fn=<MaxPool2DWithIndicesBackward>)

In [7]:
# Checking for gradients?
t = p.sum()
t.backward()

t_true = p_true.sum()
t_true.backward()

In [8]:
a.grad.data

tensor([[[[0., 1.],
          [1., 0.]]]])

In [9]:
a_true.grad.data

tensor([[[[0., 1.],
          [0., 0.]]]])